//! Low-level functions and data.
//!
//! This module contains a low-level interface used by other modules in this
//! crate. You can use it directly but it's API is less friendly and DWIMmy
//! than the higher-level APIs in other modules like [noun](crate::noun),
//! [verb](crate::verb), and [adjective](crate::adjective).
//!
//! Much of its content is generated by the [generator tool in the
//! en-inflexion
//! repo](https://github.com/houseabsolute/en-inflexion/generator).
//!
//! [This crate](super) provides a higher level interface that is more
//! convenient for many usages, but you may prefer to use the lower level
//! functions if you want to minimize allocations.

pub mod nouns;
pub mod verbs;
